# Generated by Django 5.2.3 on 2025-07-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='Puntos',
            new_name='puntos',
        ),
    
    ]
