# Generated by Django 5.2.3 on 2025-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega3', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campeones/'),
        ),
        migrations.AddField(
            model_name='escuderia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='escuderias/'),
        ),
        migrations.AddField(
            model_name='piloto',
            name='fechanac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piloto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos/'),
        ),
    ]
