# Generated by Django 5.2.3 on 2025-07-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
